name: Telegram Issue Notifier

on:
  issues:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            <b>Nueva Issue:</b>
            <b>Título:</b> ${{ github.event.issue.title }}
            <b>Autor:</b> ${{ github.event.issue.user.login }}
            
            <a href="${{ github.event.issue.html_url }}">Ir a la issue</a>
          
        

